jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000  # 24小时，单位：毫秒 

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      location: ${java.io.tmpdir}

file:
  upload:
    path: ${user.home}/company/uploads  # 使用用户目录下的固定路径
    base-url: http://localhost:8080  # 图片访问的基础URL，可以根据环境配置 